Property: add support for example
ScrumWorks/openapi-schema pull request #11
Opened 2020-11-24 01:32 UTC by detrandix

#### What's this PR do?

- Solving issue #7 
- Add support for `example` in `OA\Property`
- Do validity checking for example by schema

#### Recommendation for how to test this, or anything you are worried about?

- OpenAPI schema also support `examples` (https://swagger.io/docs/specification/adding-examples/)
- SchemaValues doesn't check example schema validity by itself (it's dumb value object...)
- Schema validity check is now do in `AnnotationPropertySchemaDecorator`, but maybe this can be done in SchemaParser before `build()` is called - but this still not solving previous problem - any suggestions?

2020-11-25 08:23 UTC, AdamLutka requested changes

2020-11-25 08:23 UTC, AdamLutka commented on src/Annotation/Property.php
> +    public ?string $example = null;
Tohle urcite nema byt string, protoze primo anotace podporuji json a chces mit moznost tam psat konstanty apod.

2020-11-25 08:23 UTC, AdamLutka commented on src/ValueSchema/AbstractValueSchema.php
> +    protected $example;
Tohle neni spolecne pro vsechna schemata, kazde schema ma example jineho typu. Plati i pro buildery, tim padem to znamena, ze ta validace je na spravnem miste, jenom ne ve spolecne metode, ale v metodach pro jednotlive buildery. Druha moznost, pokud si cheme usetrit praci, je umoznit dat jakykoliv example kamkoliv, ale v tom pripade, bych se na validaci vykaslal uplne, protoze je to pak podivny mezistav.

2022-05-11 11:43 UTC, closed without merging

2022-05-11 11:43 UTC, dada-amater commented
Task linked: [AMA-1369 OpenAPI schema parser - support for example](https://app.clickup.com/t/2439381/AMA-1369)